# Generated by Django 4.2.25 on 2025-10-30 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='backtestrecord',
            new_name='trading_bac_user_id_84e064_idx',
            old_name='trading_backtest_user_time_idx',
        ),
    ]
