# Generated by Django 4.2.25 on 2025-11-11 00:47

import json
from datetime import datetime
from pathlib import Path
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone
import django.db.models.deletion
import trading.models
import uuid

DATA_CACHE_DIR = settings.DATA_CACHE_DIR
DEFAULT_TOPIC_ID = "topic-general"
DEFAULT_TOPIC_NAME = "闲聊大厅"
PROFILE_FILE = DATA_CACHE_DIR / "user_profiles.json"
TOPIC_FILE = DATA_CACHE_DIR / "community_topics.json"
POST_FILE = DATA_CACHE_DIR / "community_posts.json"
HISTORY_FILE = DATA_CACHE_DIR / "backtest_history.json"


def _load_json(path: Path):
    if not path.exists():
        return None
    try:
        with path.open("r", encoding="utf-8") as fh:
            return json.load(fh)
    except Exception:
        return None


def _parse_timestamp(value: str | None) -> datetime:
    if not value:
        return timezone.now()
    value = value.rstrip("Z")
    for fmt in ("%Y-%m-%d %H:%M UTC", "%Y-%m-%d %H:%M:%S UTC", "%Y-%m-%dT%H:%M:%S"):
        try:
            return datetime.strptime(value, fmt).replace(tzinfo=timezone.utc)
        except ValueError:
            continue
    try:
        return datetime.fromisoformat(value).replace(tzinfo=timezone.utc)
    except ValueError:
        return timezone.now()


def migrate_legacy_data(apps, schema_editor):
    User = apps.get_model(*settings.AUTH_USER_MODEL.split("."))
    UserProfile = apps.get_model("trading", "UserProfile")
    CommunityTopic = apps.get_model("trading", "CommunityTopic")
    CommunityPost = apps.get_model("trading", "CommunityPost")
    CommunityPostComment = apps.get_model("trading", "CommunityPostComment")
    CommunityPostLike = apps.get_model("trading", "CommunityPostLike")
    BacktestRecord = apps.get_model("trading", "BacktestRecord")

    profile_payload = _load_json(PROFILE_FILE) or {}
    for user_id, data in profile_payload.items():
        try:
            user = User.objects.get(pk=user_id)
        except User.DoesNotExist:
            continue
        profile, created = UserProfile.objects.get_or_create(user=user)
        if created:
            profile.display_name = data.get("display_name") or ""
            profile.cover_color = data.get("cover_color") or "#116e5f"
            profile.bio = data.get("bio") or ""
            profile.avatar_path = data.get("avatar_path") or data.get("avatar_url") or ""
            profile.feature_image_path = data.get("feature_image_path") or data.get("feature_image_url") or ""
            gallery = data.get("gallery_paths") or []
            if isinstance(gallery, str):
                gallery = [gallery] if gallery else []
            elif not isinstance(gallery, list):
                gallery = []
            profile.gallery_paths = gallery
            profile.save()

    topic_payload = _load_json(TOPIC_FILE) or []
    for item in topic_payload:
        creator = None
        creator_label = item.get("creator_name") or ""
        creator_ref = item.get("creator_id")
        if creator_ref:
            try:
                creator = User.objects.get(pk=creator_ref)
            except (User.DoesNotExist, ValueError, TypeError):
                creator = None
        if creator and not creator_label:
            creator_label = creator.get_full_name() or creator.username
        CommunityTopic.objects.get_or_create(
            topic_id=item.get("topic_id") or f"topic-{uuid.uuid4().hex[:10]}",
            defaults={
                "name": item.get("name") or DEFAULT_TOPIC_NAME,
                "description": item.get("description") or "",
                "creator": creator,
                "creator_name": creator_label,
            },
        )

    posts_payload = _load_json(POST_FILE) or []
    for post in posts_payload:
        topic_id = post.get("topic_id") or DEFAULT_TOPIC_ID
        topic = CommunityTopic.objects.filter(topic_id=topic_id).first()
        if not topic:
            topic = CommunityTopic.objects.create(topic_id=topic_id, name=post.get("topic_name") or DEFAULT_TOPIC_NAME)
        user_id = post.get("user_id")
        try:
            author = User.objects.get(pk=user_id)
        except User.DoesNotExist:
            continue
        obj, created = CommunityPost.objects.get_or_create(
            post_id=post.get("post_id") or f"post-{uuid.uuid4().hex[:10]}",
            defaults={
                "topic": topic,
                "author": author,
                "author_display_name": post.get("author") or author.username,
                "content": post.get("content") or "",
                "image_path": post.get("image_path") or "",
                "created_at": _parse_timestamp(post.get("created_at")),
            },
        )
        if not created:
            continue
        for like in post.get("liked_by") or []:
            try:
                liker = User.objects.get(pk=like)
            except User.DoesNotExist:
                continue
            CommunityPostLike.objects.get_or_create(post=obj, user=liker)
        for comment in post.get("comments") or []:
            user_pk = comment.get("user_id")
            try:
                commenter = User.objects.get(pk=user_pk)
            except User.DoesNotExist:
                continue
            CommunityPostComment.objects.create(
                comment_id=comment.get("comment_id") or f"comment-{uuid.uuid4().hex[:10]}",
                post=obj,
                author=commenter,
                author_display_name=comment.get("author") or commenter.username,
                content=comment.get("content") or "",
                created_at=_parse_timestamp(comment.get("created_at")),
            )

    history_payload = _load_json(HISTORY_FILE) or []
    for record in history_payload:
        user_id = record.get("user_id")
        if not user_id:
            continue
        try:
            user = User.objects.get(pk=user_id)
        except User.DoesNotExist:
            continue
        timestamp = record.get("timestamp")
        try:
            parsed_ts = datetime.fromisoformat(timestamp.rstrip("Z"))
        except Exception:
            parsed_ts = timezone.now()
        BacktestRecord.objects.update_or_create(
            record_id=record.get("record_id") or uuid.uuid4().hex,
            defaults={
                "user": user,
                "timestamp": parsed_ts,
                "ticker": record.get("ticker", "UNKNOWN"),
                "benchmark": record.get("benchmark", ""),
                "engine": record.get("engine", ""),
                "start_date": record.get("start_date", ""),
                "end_date": record.get("end_date", ""),
                "metrics": record.get("metrics", []),
                "stats": record.get("stats", {}),
                "params": record.get("params", {}),
                "warnings": record.get("warnings", []),
                "snapshot": record.get("snapshot", {}),
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trading', '0002_rename_trading_backtest_user_time_idx_trading_bac_user_id_84e064_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(default=trading.models.generate_post_id, max_length=40, unique=True)),
                ('author_display_name', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('image_path', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=64)),
                ('cover_color', models.CharField(blank=True, default='#116e5f', max_length=16)),
                ('bio', models.TextField(blank=True, default='')),
                ('avatar_path', models.CharField(blank=True, default='', max_length=255)),
                ('feature_image_path', models.CharField(blank=True, default='', max_length=255)),
                ('gallery_paths', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_id', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('creator_name', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_topics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityPostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_entries', to='trading.communitypost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('post', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CommunityPostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(default=trading.models.generate_comment_id, max_length=48, unique=True)),
                ('author_display_name', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='trading.communitypost')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='communitypost',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_community_posts', through='trading.CommunityPostLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='trading.communitytopic'),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['topic', '-created_at'], name='trading_com_topic_i_fe86ab_idx'),
        ),
        migrations.RunPython(migrate_legacy_data, migrations.RunPython.noop),
    ]
