# Generated by Django 4.2.26 on 2025-12-31 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_strategy_preset'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestrecord',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='backtestrecord',
            name='starred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='backtestrecord',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='backtestrecord',
            name='title',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
