# Generated by Django 4.2.26 on 2025-12-31 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_backtest_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='market_watchlist',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
