# Generated by Django 4.2.26 on 2026-01-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_profile_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='backtest_record_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
