# Generated by Django 4.2.26 on 2026-01-17 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0010_realtime_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=12),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
