# Generated by Django 4.2.26 on 2026-01-17 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0012_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="communitypostcomment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="trading.communitypostcomment",
            ),
        ),
    ]
