# Generated by Django 4.2.26 on 2026-01-18 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0013_communitypostcomment_parent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='trading_not_recipie_945806_idx',
            old_name='trading_not_recipie_3ea86d_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='trading_not_recipie_af4d1c_idx',
            old_name='trading_not_recipie_07b26d_idx',
        ),
        migrations.RenameIndex(
            model_name='realtimeprofile',
            new_name='trading_rea_user_id_cc8c3c_idx',
            old_name='trading_rea_user_id_9a5b4e_idx',
        ),
        migrations.RenameIndex(
            model_name='realtimeprofile',
            new_name='trading_rea_user_id_6da118_idx',
            old_name='trading_rea_user_id_68d5e6_idx',
        ),
    ]
