from __future__ import annotations

from typing import Any


def user_flags(request) -> dict[str, Any]:
    user = getattr(request, "user", None)
    return {
        "is_superuser": bool(user and user.is_superuser),
        "is_staff": bool(user and user.is_staff),
    }


def csp_nonce(request) -> dict[str, Any]:
    """
    Expose the CSP nonce generated by SecurityHeadersMiddleware to templates.

    Returns an empty string when the middleware was bypassed (e.g., tests).
    """
    return {"csp_nonce": getattr(request, "csp_nonce", "")}
