from django.urls import path
from django.views.generic import RedirectView

from . import views
from .api import views_v1 as api_v1


app_name = "trading"

urlpatterns = [
    path("", RedirectView.as_view(pattern_name="trading:backtest", permanent=False)),
    path("backtest/", views.backtest, name="backtest"),
    path("paper/", views.paper_trading, name="paper_trading"),
    path("api/paper/alpaca/account/", views.paper_alpaca_account, name="paper_alpaca_account"),
    path("api/paper/alpaca/rebalance/", views.paper_alpaca_rebalance, name="paper_alpaca_rebalance"),
    path("api/screener/", views.screener_snapshot_api, name="screener_snapshot"),
    path("api/ai_chat/", views.ai_chat, name="ai_chat"),
    path("api/ai_chat/stream/", views.ai_chat_stream, name="ai_chat_stream"),
    path("api/ai/task/", views.enqueue_ai_task, name="enqueue_ai_task"),
    path("api/ai/task/<str:task_id>/", views.ai_task_status, name="ai_task_status"),
    path("api/ai/rag/ingest/", views.rag_ingest, name="rag_ingest"),
    path("api/ai/rag/query/", views.rag_query_api, name="rag_query"),
    path("api/backtest/task/", views.enqueue_backtest_task, name="enqueue_backtest_task"),
    path("api/backtest/task/<str:task_id>/", views.backtest_task_status, name="backtest_task_status"),
    path("api/backtest/<str:record_id>/fork/", views.fork_backtest, name="backtest_fork"),
    path("api/backtests/user/", views.get_user_backtests, name="get_user_backtests"),
    path("api/get_user_backtests/", views.get_user_backtests, name="get_user_backtests_legacy"),
    path("api/v1/backtests/preflight/", api_v1.PreflightView.as_view(), name="api_v1_backtest_preflight"),
    path("api/v1/backtests/tasks/", api_v1.BacktestTaskView.as_view(), name="api_v1_backtest_tasks"),
    path("api/v1/backtests/robustness/", api_v1.RobustnessTaskView.as_view(), name="api_v1_backtest_robustness"),
    path("api/v1/training/tasks/", api_v1.TrainingTaskView.as_view(), name="api_v1_training_tasks"),
    path("api/v1/rl/tasks/", api_v1.RLTaskView.as_view(), name="api_v1_rl_tasks"),
    path("api/v1/tasks/<str:task_id>/", api_v1.TaskStatusView.as_view(), name="api_v1_task_status"),
    path("api/v1/tasks/<str:task_id>/cancel/", api_v1.TaskCancelView.as_view(), name="api_v1_task_cancel"),
    path("api/v1/history/<str:record_id>/meta/", views.update_history_meta, name="api_v1_history_meta"),
    path("api/v1/presets/", api_v1.StrategyPresetView.as_view(), name="api_v1_presets"),
    path("api/v1/presets/<uuid:preset_id>/", api_v1.StrategyPresetDetailView.as_view(), name="api_v1_preset_detail"),
    path("api/v1/screener/", api_v1.ScreenerSnapshotView.as_view(), name="api_v1_screener"),
    path("api/v1/paper/sessions/", api_v1.PaperSessionView.as_view(), name="api_v1_paper_sessions"),
    path("api/v1/paper/sessions/<uuid:session_id>/", api_v1.PaperSessionDetailView.as_view(), name="api_v1_paper_session_detail"),
    path("api/v1/paper/sessions/<uuid:session_id>/trades/", api_v1.PaperSessionTradesView.as_view(), name="api_v1_paper_session_trades"),
    path("api/v1/realtime/profiles/", api_v1.RealtimeProfileView.as_view(), name="api_v1_realtime_profiles"),
    path(
        "api/v1/realtime/profiles/<uuid:profile_id>/",
        api_v1.RealtimeProfileDetailView.as_view(),
        name="api_v1_realtime_profile_detail",
    ),
    path("api/v1/realtime/signals/", api_v1.RealtimeSignalsView.as_view(), name="api_v1_realtime_signals"),
    path("api/v1/strategy/workbench/", api_v1.StrategyWorkbenchView.as_view(), name="api_v1_strategy_workbench"),
    path(
        "api/v1/strategy/workbench/trading-mode/",
        api_v1.StrategyTradingModeView.as_view(),
        name="api_v1_strategy_trading_mode",
    ),
    path(
        "api/v1/data-source/diagnose/",
        api_v1.DataSourceDiagnoseView.as_view(),
        name="api_v1_data_source_diagnose",
    ),
    path(
        "api/v1/system/api-usage/",
        api_v1.ApiUsageView.as_view(),
        name="api_v1_api_usage",
    ),
    path("api/v1/shortterm/workbench/", api_v1.ShortTermWorkbenchView.as_view(), name="api_v1_shortterm_workbench"),
    path(
        "api/v1/shortterm/trading-mode/",
        api_v1.ShortTermTradingModeView.as_view(),
        name="api_v1_shortterm_trading_mode",
    ),
    path("api/training/task/", views.enqueue_training_task, name="enqueue_training_task"),
    path("api/training/task/<str:task_id>/", views.training_task_status, name="training_task_status"),
    path("api/rl/task/", views.enqueue_rl_task, name="enqueue_rl_task"),
    path("api/rl/task/<str:task_id>/", views.rl_task_status, name="rl_task_status"),
    path("api/market/", views.market_insights_data, name="market_insights_data"),
    path("api/market/rankings/status/", views.market_rankings_status, name="market_rankings_status"),
    path("api/market/debug/auth/", views.market_auth_debug, name="market_auth_debug"),
    path("api/market/news/sentiment/", views.market_news_sentiment, name="market_news_sentiment"),
    path("api/market/chart/", views.market_chart_data, name="market_chart_data"),
    path("api/market/chart/analyze/", views.market_chart_analyze, name="market_chart_analyze"),
    path("api/market/chart/analyze/sample/", views.market_chart_analyze_sample, name="market_chart_analyze_sample"),
    path("api/market/chart/analyze/train/", views.market_chart_analyze_train, name="market_chart_analyze_train"),
    path("api/market/chart/analyze/meta/", views.market_chart_analyze_meta, name="market_chart_analyze_meta"),
    path("api/market/order/", views.market_manual_order, name="market_manual_order"),
    path("api/market/trading/", views.market_trading_mode, name="market_trading_mode"),
    path("api/market/assets/", views.market_assets_data, name="market_assets_data"),
    path("api/market/screener/", views.market_screener_data, name="market_screener_data"),
    path("api/market/watchlist/", views.market_watchlist_snapshot, name="market_watchlist_snapshot"),
    path("api/screen/analyze/", views.screen_analyzer_api, name="screen_analyzer_api"),
    path("api/screen/sample/", views.screen_analyzer_sample_api, name="screen_analyzer_sample_api"),
    path("api/screen/train/", views.screen_analyzer_train_api, name="screen_analyzer_train_api"),
    path("api/portfolio/build/", views.build_portfolio_api, name="build_portfolio"),
    path("history/delete/<str:record_id>/", views.delete_history, name="delete_history"),
    path("history/compare/", views.history_compare, name="history_compare"),
    path("export/report/", views.export_report, name="export_report"),
    path("accounts/signup/", views.signup, name="signup"),
    path("accounts/activate/<str:uidb64>/<str:token>/", views.activate, name="activate"),
    path("accounts/resend-activation/", views.resend_activation, name="resend_activation"),
    path("account/", views.account, name="account"),
    path("account/profile/update/", views.update_profile, name="account_update_profile"),
    path("account/api/update/", views.update_api_credentials, name="account_update_api_credentials"),
    path("account/api/clear/", views.clear_api_credentials, name="account_clear_api_credentials"),
    path("account/password/reset/", views.reset_password, name="account_reset_password"),
    path("account/avatar/delete/", views.delete_avatar, name="account_delete_avatar"),
    path("account/feature/delete/", views.remove_feature, name="account_remove_feature"),
    path("account/gallery/remove/", views.remove_gallery, name="account_remove_gallery"),
    path("realtime/settings/", views.realtime_settings, name="realtime_settings"),
    path("realtime/monitor/", views.realtime_monitor, name="realtime_monitor"),
    path("market/", views.market_insights, name="market_insights"),
    path("screen/analyzer/", views.screen_analyzer, name="screen_analyzer"),
    path("learning/", views.learning_center, name="learning_center"),
    path("learning/<slug:slug>/", views.learning_module_detail, name="learning_detail"),
    path("community/", views.community, name="community"),
    path("community/notifications/", views.community_notifications, name="community_notifications"),
    path("community/write/", views.write_post, name="community_write"),
    path("community/write/<int:post_id>/", views.write_post, name="community_edit_draft"),
    path("community/drafts/", views.get_user_drafts, name="community_drafts"),
    path("community/delete/<int:post_id>/", views.delete_post, name="delete_post"),
    path("community/like/", views.community_like, name="community_like"),
    path("community/comment/", views.community_comment, name="community_comment"),
    path("community/delete/", views.community_delete, name="community_delete"),
    path("profile/<uuid:profile_slug>/", views.profile_public, name="profile_public"),
    path("observability/", views.observability_dashboard, name="observability"),
]
