# Generated by Django 4.2.26 on 2025-11-22 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='papertrade',
            new_name='paper_paper_session_7c55ed_idx',
            old_name='paper_paper_session__015048_idx',
        ),
        migrations.RenameIndex(
            model_name='papertradingsession',
            new_name='paper_paper_user_id_18ada6_idx',
            old_name='paper_paper_user_id_a1109b_idx',
        ),
        migrations.RenameIndex(
            model_name='papertradingsession',
            new_name='paper_paper_status_bb8717_idx',
            old_name='paper_paper_status__1cd6ac_idx',
        ),
    ]
